# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_day: nadeau
  font: minimal
  font_size: L

# SEO
marketing:
  seo:
    site_type: LocalBusiness
    local_business_type: ProfessionalService
    org_name: ''
    # NN: max ~160 characters description for SEO
    description: "Unlock Your Hard Tech Potential: We empower startups and corporate innovation with fractional CTO expertise."
    twitter: 'NadeauInnov'
  analytics:
    google_analytics: 'UA-60125866-2'
    baidu_tongji: ''
  # NN: currently verified using namecheap Domain name provider
  # https://search.google.com/u/1/search-console/ownership?resource_id=sc-domain%3Anicholasnadeau.com
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: true
    highlight_active_link: true

# Site footer
footer:
  widget: minimal
  copyright:
    notice: '© {year} Nadeau Innovations.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - latex
      - python
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/nadeau-innovations/site'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    wowchemy:
      # Only the matches whose length exceeds this value will be returned.
      min_length: 1
      # Where 0 requires a perfect match and 1 matches anything.
      threshold: 0.3
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions
extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true

# Companiess Widget
companies:
  - icon: acrylic
    url: https://acrylicrobotics.ca/
  - icon: airbotics
    url: https://www.airbotics.io/
  - icon: bridgr
    url: https://bridgr.co/
  - icon: citera
    url: https://www.citera.ai/
  - icon: femtherapeutics
    url: https://femtherapeutics.com/
  - icon: fundica
    url: https://www.fundica.com/
  - icon: gratified
    url: https://gratified.io/
  - icon: interius-farms
    url: https://interiusfarms.com/
  - icon: osedea
    url: https://interiusfarms.com/
  - icon: pivot-edge
    url: https://www.pivotandedge.com/
  - icon: rdp
    url: https://www.rdpartners.com/
  - icon: smartone
    url: https://smartone.ai/
  - icon: xprlabs
    url: https://xprlabs.com/

testimonials:
  - name: Andrew Murtagh
    position: CEO & Co-Founder
    organization: Airbotics
    image: andrew.jpg
    quote: "Nick has been enormously helpful to us at Airbotics. He has unmatched expertise in all things robotics and AI at the highest levels, a very deep network in the field, and years of experience in the trenches of startups building and selling deep tech products. Not only that, but he's always your biggest fan and brings such energy and enthusiasm to whatever challenges you're facing. If you're building in the robotics space or want to learn about it - talk to Nick!"
    url: https://airbotics.io/
  - name: Tristan Zeman
    position: President & Co-Founder
    organization: Interius Farms
    image: tristan.jpg
    quote: "Working with Nick has been game-changing for our company's technology development. His expertise and strategic thinking have been instrumental in setting up our automation strategy. Nick has a unique ability to bridge the gap between technology and business goals. Nick is exceptionally well connected to the tech startup ecosystem in Montreal across academia, manufacturing, fabrication, etc. If he does not have an answer, he knows someone who does; he is always willing to make introductions to facilitate valuable partnerships."
    url: https://interiusfarms.com/
  - name: Daniel Lirette
    position: Founder & CEO
    organization: GrowDoc
    image: daniel.jpg
    quote: "Nicholas holds a wealth of knowledge regarding technology, AI, robotics, and more. He has guided us in anticipating and devising strategies for future challenges before they arise. He is always straight to the point and professional. I look forward to working with him again in the future!"
    url: https://growdoc.ca/
  - name: Mohamed Ashraf
    position: Co-Founder & Product Lead
    organization: Ohmic
    image: mohamed.jpg
    quote: "Nicholas was incredibly helpful and supportive to both us as founders and the entire team. Nicholas was an active, hands-on supporter and friend to Ohmic, who invested his time towards offering us feedback, inviting us to networking events, and even introducing us to our first external angel investor. We are lucky to have worked with Nicholas and are glad to have connected with him."
    url: https://www.ohmictechnologies.com/
  - name: Thierry Marcoux
    position: Head of Business Development
    organization: Osedea
    image: thierry.jpg
    quote: "Nicholas brings tremendous value to the company with his deep knowledge of robotics and AI. He conducts internal Lunch & Learns, facilitates crucial network connections, and contributes substantially to Osedea's key projects. Additionally, he's a pleasure to work with!"
    url: https://www.osedea.com/
