# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_day: nadeau
  font: minimal
  font_size: L

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    # NN: max ~160 characters description for SEO
    description: Nicholas Nadeau helps companies build next-generation technologies and empowers high-performance teams through Fractional CTO services.
    twitter: 'EngNadeau'
  analytics:
    google_analytics: 'UA-60125866-2'
    baidu_tongji: ''
  # NN: currently verified using namecheap Domain name provider
  # https://search.google.com/u/1/search-console/ownership?resource_id=sc-domain%3Anicholasnadeau.com
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: true
    highlight_active_link: true

# Site footer
footer:
  widget: minimal
  copyright:
    notice: '© {year} Nicholas Nadeau. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - latex
      - python
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/engnadeau/nadeau-innovations-site'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    wowchemy:
      # Only the matches whose length exceeds this value will be returned.
      min_length: 1
      # Where 0 requires a perfect match and 1 matches anything.
      threshold: 0.3
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions
extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true
