[build]
publish = "public"
command = "make build"

[build.environment]
HUGO_VERSION = "0.95.0"
HUGO_ENABLEGITINFO = "true"

# If skip_processing = true, all other settings are ignored
[build.processing]
skip_processing = false

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[[plugins]]
# https://github.com/netlify/netlify-plugin-lighthouse
package = "@netlify/plugin-lighthouse"
  
  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.8

[[plugins]]
# https://github.com/netlify-labs/netlify-plugin-sitemap
package = "@netlify/plugin-sitemap"
