[build]
publish = "public"
command = "make build"

[build.environment]
HUGO_VERSION = "0.104.3"
HUGO_ENABLEGITINFO = "true"

# If skip_processing = true, all other settings are ignored
[build.processing]
skip_processing = false

[build.processing.css]
bundle = true
minify = false

[build.processing.js]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[[plugins]]
# https://github.com/netlify/netlify-plugin-lighthouse
package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.6
    accessibility = 0.9
    best-practices = 0.8
    seo = 0.9
    pwa = 0.8

[[plugins]]
# https://github.com/netlify-labs/netlify-plugin-sitemap
package = "@netlify/plugin-sitemap"

# https://docs.netlify.com/configure-builds/file-based-configuration/#redirects
[[redirects]]
from = "https://www.nicholasnadeau.me"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://nicholasnadeau.me"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://www.nicholasnadeau.com"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://www.nicholasnadeau.com"
to = "https://nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://www.n2innovations.com"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://n2innovations.com"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://www.engnadeau.com"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://engnadeau.com"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://techbattlecards.com"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://www.techbattlecards.com"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://www.pythonhardware.com"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://pythonhardware.com"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://www.hardtechinnovations.com"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://hardtechinnovations.com"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://www.hardtech.news"
to = "https://www.nadeauinnovations.com"
status = 301
force = true

[[redirects]]
from = "https://hardtech.news"
to = "https://www.nadeauinnovations.com"
status = 301
force = true
