on:
  push:
    branches:
      - master
      - next
      - beta
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18
      - run: npx --yes semantic-release@20
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
